export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"



export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS__REQUEST";
export const PRODUCT_DETAILS__SUCCESS = "PRODUCT_DETAILS__SUCCESS";
export const PRODUCT_DETAILS__FAIL = "PRODUCT_DETAILS__FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE__REQUEST";
export const PRODUCT_DELETE__SUCCESS = "PRODUCT_DELETE__SUCCESS";
export const PRODUCT_DELETE__FAIL = "PRODUCT_DELETE__FAIL";