export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"



export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS__REQUEST";
export const PRODUCT_DETAILS__SUCCESS = "PRODUCT_DETAILS__SUCCESS";
export const PRODUCT_DETAILS__FAIL = "PRODUCT_DETAILS__FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE__REQUEST";
export const PRODUCT_DELETE__SUCCESS = "PRODUCT_DELETE__SUCCESS";
export const PRODUCT_DELETE__FAIL = "PRODUCT_DELETE__FAIL";


export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE__REQUEST";
export const PRODUCT_CREATE__SUCCESS = "PRODUCT_CREATE__SUCCESS";
export const PRODUCT_CREATE__FAIL = "PRODUCT_CREATE__FAIL";
export const PRODUCT_CREATE__RESET = "PRODUCT_CREATE__RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE__REQUEST";
export const PRODUCT_UPDATE__SUCCESS = "PRODUCT_UPDATE__SUCCESS";
export const PRODUCT_UPDATE__FAIL = "PRODUCT_UPDATE__FAIL";
export const PRODUCT_UPDATE__RESET = "PRODUCT_UPDATE__RESET";